version: '3.3'
services:
  comment:
    command: puma --debug -w 2
    volumes:
      - comment:/app
  ui:
    command: puma --debug -w 2
    volumes:
      - ui:/app
  post:
    volumes:
      - post:/app

volumes:
  ui:
  comment:
  post:
