kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: cfPGGJFKQOI/+UY5dLyprKnALOSkAy7HItK6GJOTjZg=
      - identity: {}
